services:
  vault:
    build: 
      dockerfile: Dockerfile.vault
      context: .
    ports:
      - 8000


  postgres:
    image: "mirror.gcr.io/postgres:17"
    ports:
      - 5432
    volumes:
      psql:
