services:
  vault:
    build: 
      dockerfile: Dockerfile.vault
      context: .
    ports:
      - 8000:8000


  postgres:
    build: 
      dockerfile: Dockerfile.postgres
      context: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  pgdata: