services:
  vault:
    build: 
      dockerfile: Dockerfile.vault
      context: .
    ports:
      - 8000:8000


  postgres:
    image: "mirror.gcr.io/postgres:17"
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  psql_data:
