name: Deploy to Server

on:
  push:
    branches-ignore: main  # Ignore production, only deploy dev branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker on GitHub runner
      uses: docker/setup-buildx-action@v2

    - name: Deploy branch to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        BRANCH_NAME: ${{ github.ref_name }}  # The branch name
      run: |
        # Setup SSH
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        # Send the source code to the server
        scp -i private_key.pem -r ./ $SERVER_USER@$SERVER_IP:$HOME/vault/${BRANCH_NAME}/

        # SSH into the server and build and deploy the Docker container there
        ssh -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          cd $HOME/vault/${BRANCH_NAME}/

          # Build the Docker image on the server itself
          docker-compose build

          # Stop any existing container with the same name
          docker-compose down

          # Run the Docker container for this branch
          docker-compose up -d
        EOF